### PR TITLE
global: addition of .idea/ folder to .gitignore

### PR DESCRIPTION
**Pull request by bruno314**
Signed-off-by: Bruno Cuc <bruno.cuc@cern.ch>

### CODE REVIEW

**Comment by jirikuncar** [comment]
`s/Added/addition/`

**Comment by lnielsen** [comment]
@bruno314 Will you update the commit message so that we can merge this one.

**Comment by jirikuncar** [comment]
https://github.com/inveniosoftware/cookiecutter-invenio-module/pull/37#issuecomment-154440283
`s/Addition/addition/`

**Comment by tiborsimko** [comment]
@bruno314 Note that there is extra leading space in front of `* ` that should be eliminated.  Please also rebase against latest master.

**Comment by bruno314** [comment]
Fixed.

**Pull request merged**
