### PR TITLE
global: license fix

### LINKED ISSUE #3: fix licence headers
- [ ] `# This file is part of {{ project or Invenio ? }}.`
- [ ] fix other mentions of Invenio in the header
- [ ] empty line before docstring

### PR DESCRIPTION
**Pull request by crepererum**
* Extracts license headers to dedicated files.

* Adds superproject parameter which is used for license purposes.

* Adds empty line between license header and first content line.

* Adds license to rst files.

* Clarifies that this project is part of Invenio.

* Closes #3.

Signed-off-by: Marco Neumann <marco@crepererum.net>

### CODE REVIEW

**Comment by jirikuncar** [comment]
@crepererum can we move `docs/source` to `docs`? Btw you are using import in `docs/source/conf.py`, I'm not sure if it's safe ...

**Comment by crepererum** [comment]
@jirikuncar 
> can we move docs/source to docs?

we can, but this should not be part of this PR.

> Btw you are using import in docs/source/conf.py, I'm not sure if it's safe ...

What do your think should the alternative look like? My approach uses the mocking library to mock all imports that are done by the `version` module. If we really do some heavy lifting in that module and import a lot of other stuff, then we should really think about the purpose of `version`, because it should only give the version and not do any other initialization, right?

From Invenio `master`:
```
# Get the version string. Cannot be done with import!
g = {}
with open(os.path.join('..', 'invenio', 'version.py'), 'rt') as fp:
    exec(fp.read(), g)
version = g["__version__"]
```
This does not feel any better.

**Comment by lnielsen** [comment]
The problem is usually not with ``version.py`` but anything along the way to it, which usually boils down to ``invenio_<module>/__init__.py`` that may have imports that cascade widely. 

Also I'm not sure about the details, but perhaps if you want to build the docs without having a working installation then the import will fail?

I'm would prefer that the same method is used in both ``setup.py`` and ``docs/conf.py``, and that it's aligned with all existing packages that we have released.

**Comment by crepererum** [comment]
@lnielsen You are, this will lead to the `import all` chain. So we can use the hack stated above to get the version. BTW don't mix the the problem that is used for gathering the version information and the system that should help autodoc to build a useful documentation even when you don't provide all dependencies.

**Comment by crepererum** [comment]
Discussion about documentation related stuff gets moved to #9.

**Pull request merged**
