### PR TITLE
manifest: translation files inclusion

### PR DESCRIPTION
**Pull request by lnielsen**
* Adds compiled translations files into Python package so that they
  can be distributed on PyPI.

Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>

### CODE REVIEW

**Comment by nharraud** [comment]
I see that Invenio's `Manifest.in` also includes `*.pot` files. Is there a reason why we don't want them anymore?

**Comment by jirikuncar** [comment]
:shipit:

**Comment by lnielsen** [comment]
@nharraud I honestly don't remember the exact reason anymore, but I think it was because only the mo/po files are needed in the python package itself. @jirikuncar do you remember better than me?

**Comment by jirikuncar** [comment]
The `*.pot` file is used only to generate new catalog for language. We can include it but it will only occupy space in the distribution package.

**Comment by nharraud** [comment]
ok, :shipit:

**Pull request merged**
